### ISSUE TITLE
Hive 3.0 isn't compatible with hive generator

### ISSUE THREAD

**Issue by Macacoazul01** [isar/hive#1117]
@themisir hive packages aren't compatible with the new upgrades:

using 
`hive_generator: 2.0.0`
`hive: 3.0.0-dev`
`hive_flutter: 2.0.0-dev`

I'm having this error:

```
Because hive_generator >=1.1.0 depends on hive ^2.0.4 and loginfertplanapp depends on hive 3.0.0-dev, hive_generator >=1.1.0 is forbidden.
So, because loginfertplanapp depends on hive_generator 2.0.0, version solving failed.
pub get failed (1; So, because loginfertplanapp depends on hive_generator 2.0.0, version solving failed.)
```

**Comment by abhay-s-rawat** [comment]
I am also facing same issue.

**Comment by themisir** [comment]
You all can specify `dependency_overrides` on the `pubspec.yaml` to force `hive@3.0.0-dev`.

- Why `hive_generator` peer dependencies have not been updated yet?

  Because `hive@3.0.0-dev` is not a stable release. I can not provide compatibility guarantees for unstable releases unfortunately.

- When the `hive@3.0.0-dev` version will be bumped to the stable stage?

  Unfortunately I can't provide any ETA. I am currently working on [nested type adapters](https://github.com/hivedb/hive/pull/1134) on my spare time. I am planning to release hive 3.0 alongside with the nested registries support. The feature is mostly implemented, there's just a few web related issues needs to be solved. After all tests have been passed successfully I am planning to release it publicly as a stable version.

**Comment by rezadevelopers2** [comment]
Problem not solved?

**Comment by Macacoazul01** [comment]
Closing as this wont be fixed
